// This function accepts a pre-sorted array and then returns that array without any duplicates
function RemoveDuplicates(myArray)
{
var result=new Array();
var lastValue="";
	for (var i=0; i < myArray.length; i++)
    {
 		var curValue=myArray[i];
		if (curValue != lastValue)
  		{
		result[result.length] = curValue;
 		}
	lastValue=curValue;
    }
	return result;
}

// This function uses the Fisher Yates algorithm to randomly shuffle an array. (Source code from http://sedition.com/perl/javascript-fy.html.) I use it to shuffle the  mediatorIDsForUniqueLocale[selectedlocalevalue] array in the LocaleBasedInfoDumper() function to ensure that in cases of a locale having multiple mediators, the mediators.shtml displays those mediators in a random order down the page. 
// Note: this function modifies its input parameter 'myArray'. The modified version of myArray is the de facto output of the function. I don't like this style of parameter passing.
function FisherYates(myArray)
{
  var i = myArray.length;
  if ( i == 0 ) return false;
  while ( --i ) { // I don't understand the syntax of this exit expression
     var j = Math.floor( Math.random() * ( i + 1 ) );
     var tempi = myArray[i];
     var tempj = myArray[j];
     myArray[i] = tempj;
     myArray[j] = tempi;
   }
}

//Function that uses contents of the states array (a 2D [n rows x 2 cols] array containing the full state abbreviation [e.g. NM] and the full state name [e.g. New Mexico]) to generate a drop-down list of states. This is a sister function to GenerateLocalesDrop().
function GenerateStatesDrop()
{
// String together the HTML for the drop-down list using a for loop to process the states in this select HTML element. 
var statesDropHTML = "";
if (IEBrowserCheck() == false) { statesDropHTML = "<br>" } // Add a line of extra space between the <h1> heading and the states drop-down menu if the browser is not IE. Do this because IE tends to space things more generously that Firefox/NS/Safari.
statesDropHTML += "<span class='basictextbold'>Your State:&nbsp;&nbsp;</span>";
statesDropHTML += "<select name='statesdrop' id='statesdrop' size='1' style='font-size: 12px; font-weight:normal; font-family:Arial,Helvetica,\'Century Gothic\', sans-serif' onChange='SetCookie(\"selectedstate\",this.value,\"\",\"\"); ShowHideDivDirectorStates(form);'>";  // On change, set a cookie to capture the selected state's value from the states drop-down menu named 'statesdrop'.
statesDropHTML += "<option value='' selected><&nbsp;Select a State&nbsp;></option>"; // When no state is selected, the value is 'null' i.e. ''.
var count;
for (count=0; count< numberOfStates; count++)
	{
	statesDropHTML += "<option value='";
	statesDropHTML += states[count][0];
	statesDropHTML += "'>";
	statesDropHTML += states[count][1];
	statesDropHTML += "</option>";
	}
statesDropHTML += "</select>";
return statesDropHTML;
}

/* Function that directs which div ID is shown (i.e. has its display style attributes turned onto 'block' by the showAll() function in dynamicformutility.js) while all the other div IDs are hidden (i.e. have their display style attributes set to 'none' by the hideAll() function). This function acts as a traffic cop. It is invoked with every change in the states dropdown menu that's generated by function GenerateStatesDrop().
Note: I've repeated very similar traffic cop functionality in function PresetStatesDropSelection().
Note: function ShowHideDivDirectorLocales() is a sister of ShowHideDivDirectorStates(). */
function ShowHideDivDirectorStates(form)
{
var selectedstatevalue;
var index;
HideStateDivs(); // Hide everything i.e. hide the instructions div and any state div (e.g. div="TX" for Texas).
selectedstatevalue = form.statesdrop.value; // Assign selectedstatevalue to the value of the user-selected state in the statesdrop form element. Note that if the selection is 'no state selected', the value is a null value of "").
if (selectedstatevalue != "")
	{
		if (customtitleflag) // Some pages (e.g. support.shtml) have custom h1 titles (e.g. due to different names for 'spousal support'). The custom name is stored as the third column in the states[row][col] array.
		{
			for (index in states)
			{
			if (states[index][0] == selectedstatevalue) 
				{
				document.getElementById('custom_title_pen').innerHTML = states[index][2];
				break;
				}
			}
		}
	showAll(selectedstatevalue);
	showAll('notice_pen');
	IncludeNotice('notice_pen');
	}
else // The statesdrop drop-down menu is in the neutral position.
	{
		if (customtitleflag) document.getElementById('custom_title_pen').innerHTML = customtitledefault; // Set custom title to default value (defined in the shtml page) if selectedstatevalue == "" i.e. if statesdrop drop-down menu is at neutral position.
		showAll("instructions"); //If the user resumes the 'Select a State' setting on the states drop-down menu, then show the div with id="instructions" again.
		hideAll('notice_pen');
	}
return;
}


//Function that presets the selected item in the 'statesdrop' dropdown menu according to the value of the "selectedstates" cookie. This is a sister function to PresetLocalesDropSelection().
function PresetStatesDropSelection()
{
var list = document.getElementById('statesdrop');
var counter;
var selectedstatevalue;
var valueofstatescookie;
// Test the cookie. If a cookie string exists AND that string includes a 'selectedstate' cookie AND the value of the 'selectedstate' cookie isn't "" (used by Firefox) AND the value of the 'selectedstate' cookie isn't null (used by IE) then assign the 'selectedstate' cookie's value to valueofstatescookie; else, assign "" to  valueofstatescookie.
if (document.cookie && document.cookie.indexOf("selectedstate") > -1 && GetCookieValue("selectedstate") != "" && GetCookieValue("selectedstate") != null)
	{
	valueofstatescookie = GetCookieValue("selectedstate");
	}
else
	{
	valueofstatescookie = "";
	}
for (counter = 0; counter < list.options.length; counter++) // Note that if the states array has, say, six states in it, then I'd have seven options (the six states plus one extra for the 'Select a State' option [whose value is ""]). Therefore, list.options.length will be six, remembering that the length count of this array starts at zero.
	{
	if (list.options[counter].value == valueofstatescookie) 
		{
		list.options[counter].selected = true;
		selectedstatevalue = list.options[counter].value; // Store the selected value in variable selectedstatevalue, which I'll use later in this function to make a show/hide decision (similar to the one made in function ShowHideDivDirectorStates()).
		break;
		}
	}
if (selectedstatevalue != "")
	{
		if (customtitleflag) // Some pages (e.g. support.shtml) have custom h1 titles (e.g. due to different names for 'spousal support'). The custom name is stored as the third column in the states[row][col] array.
		{
			for (index in states)
			{
			if (states[index][0] == selectedstatevalue) 
				{
				document.getElementById('custom_title_pen').innerHTML = states[index][2];
				break;
				}
			}
		}
		HideStateDivs(); // Hide everything i.e. hide the instructions div and any state div (e.g. div="TX" for Texas).
		showAll(selectedstatevalue);
	}
else // The statesdrop drop-down menu is in the neutral position.
	{
		if (customtitleflag) document.getElementById('custom_title_pen').innerHTML = customtitledefault; // Set custom title to default value (defined in the shtml page) if selectedstatevalue == "" i.e. if statesdrop drop-down menu is at neutral position.
		showAll("instructions"); //If the statesdrop dropdown menu is set to the option of 'Select a State' (i.e. selectedstatevalue is ""), then show the div with id="instructions" again.
	}
return;
}

/* Function that uses contents of the uniqueLocaleLabel array to generate a drop-down list of unique locale labels. This function is VERY similar to function GenerateUniqueLocaleDrop(). Also note that GenerateLocalesDrop() is a cousin of GenerateStatesDrop(). GenerateLocalesDrop() gets used on pages s_fees.shtml, s_mediators.shtml, and c_contact whereas GenerateUniqueLocaleDrop() gets used on consultreqform.shtml, c_inpersonconsultreqform.shtml, otherpartyrequestform.shtml, and c_schedmediationform.shtml. Note that the s_mediators.shtml page is a page whose drop-down menu redirects to custom mediator .shtml pages e.g. mediatorSanFrancisco-Oakland-Fremont.shtml. */
function GenerateLocalesDrop()
{
// String together the HTML for the drop-down list using a for loop to process the states in this select HTML element. 
var localesDropHTML = "";
if (IEBrowserCheck() == false) { localesDropHTML = "<br>" } // Add a line of extra space between the <h1> heading and the states drop-down menu if the browser is not IE. Do this because IE tends to space things more generously that Firefox/NS/Safari.
localesDropHTML += "<span class='basictextbold'>Your Locale:&nbsp;&nbsp;</span>";
localesDropHTML += "<select name='localesdrop' id='localesdrop' size='1' style='font-size: 12px; font-weight:normal; font-family:Arial,Helvetica,\'Century Gothic\', sans-serif' onChange='if (this.value == \"\") { SetCookie(\"selectedlocale\",\"\",\"\",\"\"); SetCookie(\"selectedlocalelabel\",\"\",\"\",\"\"); SetCookie(\"selectedmediator\",\"\",\"\",\"\"); SetCookie(\"selectedstate\",\"\",\"\",\"\"); LocaleBasedInfoDumper(this.value); } else { SetCookie(\"selectedlocale\",uniqueLocale[uniqueLocaleLabel[this.value][1]],\"\",\"\"); SetCookie(\"selectedlocalelabel\",uniqueLocaleLabel[this.value][0],\"\",\"\"); if (mediatorIDsForUniqueLocaleLabel[this.value].length == 1) SetCookie(\"selectedmediator\",mediatorIDsForUniqueLocaleLabel[this.value][0],\"\",\"\"); else  SetCookie(\"selectedmediator\",\"\",\"\",\"\"); LocaleBasedInfoDumper(uniqueLocaleLabel[this.value][1]); if (mediatorspageflag) {mediatorspageflag = false; var destinationURL = \"mediator\" + uniqueLocaleLabelAssocStub[this.value] + \".shtml\"; top.location.href = destinationURL; }; if (feespageflag) {feespageflag = false; var destinationURL = \"mediationcost\" + uniqueLocaleLabelAssocStub[this.value] + \".shtml\"; top.location.href = destinationURL; } }; '>";  // On change, set a cookie to capture the name of the selected locale and locale label by looking them up in the uniqueLocale and uniqueLocaleLabel arrays respectively. Also set the selectedmediator cookie if I can determine that the selected locale label pertains to a single mediator ID, otherwise set the selectedmediator cookie to null. (Seek this determination by assessing the length of the mediatorIDsForUniqueLocaleLabel array. Finally, call LocaleBasedInfoDumper() to direct what information [e.g. mediator(s) profile(s) or mediator(s) fees or mediator(s) contact info]  should be dumped into holding_pen1.
localesDropHTML += "<option value='' selected><&nbsp;Select a Locale&nbsp;></option>"; // When no locale label is selected, the value is ''.
var index, trunc;
for (index=0; index < uniqueLocaleLabel.length; index++)
	{
	localesDropHTML += "<option value='";
	localesDropHTML += index;
	localesDropHTML += "'>";
// Append the corresponding two-letter state abbreviation to the locale in the drop-down menu display of options unless the corresponding state is 'US', in which case don't display the state.
	if (uniqueLocaleLabelState[index] != "US") 
		{  
		localesDropHTML += uniqueLocaleLabel[index][0].replace('_', ', '); 
		}
	else
		{
		// Truncate the '_US' suffix from the uniqueLocaleLabel
		trunc = uniqueLocaleLabel[index][0].split('_'); trunc = trunc[0];
		localesDropHTML += trunc; 
		}
	localesDropHTML += "</option>";
	}
localesDropHTML += "</select>";
return localesDropHTML;
}

/*
Function LocaleBasedInfoDumper(index) is called on change of the GenerateLocalesDrop() function and by PresetLocalesDropSelection() for the mediators.shtml page. It's also called briefly by the c_contact.shtml and s_fees.shtml pages.
*/
function LocaleBasedInfoDumper(index)
{
var localeBasedInfoHTML = "";
var selectedlocalevalue, ID;
var hrly, hrlyHalf, pkgLength, count, ix; // I think hrly, hrlyHalf, and pkgLength serve no purpose here.
var cnsltPcy = new Array();
selectedlocalevalue = index; // Assign selectedlocalevalue to the value of the index value selected by the user in the localesdrop form element. This value could be "" (if the selection is 'no locale selected', the value is "") or it could be an index value of the uniqueLocale array.
hideAll("instructions");
hideAll("holding_pen1");
if (mediatorspageflag)
	{
	if (selectedlocalevalue != "")
		{
		/*	
		localeBasedInfoHTML += "<p class='text'>We are specialists in conflict resolution. We take great pride in the quality of our mediators, and we back this pride with professional training, continuing education, and many years experience. We have graduate degrees in related disciplines such as conflict studies, international relations, and psychology. And, when appropriate, we refer mediation clients to other independent and complementary professionals such as attorneys, CPAs, and therapists for legal counsel, financial expertise, and emotional support.</p>";
		localeBasedInfoHTML += "<HR align='left' size='1px' noshade color='#FF9900' class='formdivider4'>";
		*/
		num = 1; // A count variable used to determine whether to draw horz line between mediator profiles.
		localeBasedInfoHTML += "<table width='750' cellpadding='0' cellspacing='0'>";
		FisherYates(mediatorIDsForUniqueLocale[selectedlocalevalue]) // Call FisherYates function to shuffle the contents of mediatorIDsForUniqueLocale[selectedlocalevalue], thereby ensuring that mediator profiles get displayed on mediators.shtml in random order if a locale has more than one mediator i.e. if there's more than one ID item in the mediatorIDsForUniqueLocale[selectedlocalevalue] array.
		for (ix in mediatorIDsForUniqueLocale[selectedlocalevalue])  // Note: the mediatorIDsForUniqueLocale[selectedlocalevalue] array has now had its elements shuffled.
			{
			ID = mediatorIDsForUniqueLocale[selectedlocalevalue][ix];
			localeBasedInfoHTML += "<tr>";
			localeBasedInfoHTML += "<td width='150' rowspan='2'>&nbsp;</td>";
			localeBasedInfoHTML += "<td width='315'>";
			localeBasedInfoHTML += "<h2 class='leftcol'><a name='med" + ID + "'></a>"; // Internal hyperlink
			if (mediatorIDsForUniqueLocale[selectedlocalevalue].length > 1) localeBasedInfoHTML += num + ".&nbsp;";
			localeBasedInfoHTML += NewResolution.mediators[ID].getMediatorName();
			if (NewResolution.mediators[ID].getMediatorCred() != '') { localeBasedInfoHTML += ", " + NewResolution.mediators[ID].getMediatorCred() }; // Only append a mediator's credential if he/she has one.
			localeBasedInfoHTML += "</h2>";
			localeBasedInfoHTML += "<div class='greytext'>";
			if (NewResolution.mediators[ID].getMediatorPrincipalStreet() != "") localeBasedInfoHTML += NewResolution.mediators[ID].getMediatorPrincipalStreet() + ", ";
			if (NewResolution.mediators[ID].getMediatorPrincipalAddressOther() != "") localeBasedInfoHTML += NewResolution.mediators[ID].getMediatorPrincipalAddressOther() + ", ";
			if (NewResolution.mediators[ID].getMediatorCity() != "") localeBasedInfoHTML += NewResolution.mediators[ID].getMediatorCity();
			if (NewResolution.mediators[ID].getMediatorTelephone() != "") 
				{
				localeBasedInfoHTML += "; tel.&nbsp;" + NewResolution.mediators[ID].getMediatorTelephone(); 
				};
			localeBasedInfoHTML += "</div>";
			localeBasedInfoHTML += "</td>";
			localeBasedInfoHTML += "<td align='right' valign='top' width='160px'>";
			localeBasedInfoHTML += "<a id='size11' href='c_contact.shtml";
if (mediatorIDsForUniqueLocale[index].length >1) localeBasedInfoHTML += "#med" + ID; // Append the internal hyperlink anchor if there will be more than one mediator listed on the destination page.
localeBasedInfoHTML += "' onclick='SetCookie(\"selectedmediator\"," + NewResolution.mediators[ID].getMediatorID() + ",\"\",\"\")'>";
			if (NewResolution.mediators[ID].getMediatorName().length < 22) // Not an extraordinaryily long name.
				localeBasedInfoHTML += "Contact " + NewResolution.mediators[ID].getMediatorName() + "</a><br/>";
			else // An extraordinarily long name that may cause formatting overrun inside this <td> table cell...
				{
				var startpos;
				if (NewResolution.mediators[ID].getMediatorName().indexOf(". ")==-1) startpos=0; else startpos = NewResolution.mediators[ID].getMediatorName().indexOf(". ") + 2; // Deal with special case of name of type J. Edgar Hoover.
				var spacepos = NewResolution.mediators[ID].getMediatorName().search(/[a-z] /);
				localeBasedInfoHTML += "Contact " + NewResolution.mediators[ID].getMediatorName().substring(startpos,spacepos+1) + "</a><br/>"; // ... so just use the first part of the mediator's name inside the hyperlink tag, up to the first space.
				}
			localeBasedInfoHTML += "<a id='size11' href='s_fees.shtml' onclick='SetCookie(\"selectedmediator\"," + NewResolution.mediators[ID].getMediatorID() + ",\"\",\"\")'>Fees</a></td>";
			localeBasedInfoHTML += "<td width='125' rowspan='3' valign='top'>";
			localeBasedInfoHTML += "<img onerror='this.src=\"/images/BlankSubForBrokenImage.jpg\"' style='position: relative; top:"; // Use the onerror event handler to avoid the red x that IE produces when the mediator hasn't uploaded an image. (Fix provided by www.tech-evangelist.com/2007/09/15/missing-image-fix)
			switch (NewResolution.mediators[ID].getMediatorLocations().length) // Align jpg for cases with no additional 'satellite locations' grey text line and for Safari spacing.
			{
			case 1:
				if (SafariBrowserCheck()) localeBasedInfoHTML += "31px' src='images/Mediator" + ID + ".jpg'  width='100' height='120' align='right'>"; else localeBasedInfoHTML += "37px' src='images/Mediator" + ID + ".jpg'  width='100' height='120' align='right'>";
				break;
			default:
				if (SafariBrowserCheck()) localeBasedInfoHTML += "47px' src='images/Mediator" + ID + ".jpg'  width='100' height='120' align='right'>"; else localeBasedInfoHTML += "54px' src='images/Mediator" + ID + ".jpg'  width='100' height='120' align='right'>";
				break;
			}
			localeBasedInfoHTML += "</td>";
			localeBasedInfoHTML += "</tr>";
			localeBasedInfoHTML += "<td colspan='2' width='475'>";
			localeBasedInfoHTML += "<div class='greytext'>";
			if (NewResolution.mediators[ID].getMediatorLocations().length > 1) 
			{
				count = 0;
				localeBasedInfoHTML += "<div style='margin-top: 4px'>Locations: " + NewResolution.mediators[ID].getMediatorLocations()[count];
				count = 1;
				do
				{
					localeBasedInfoHTML += ", " + NewResolution.mediators[ID].getMediatorLocations()[count];
					count +=1;
				}
				while (NewResolution.mediators[ID].getMediatorLocations().length > count);
			}
			localeBasedInfoHTML += "</div>";
			if (IEBrowserCheck()) localeBasedInfoHTML += "<br/>";
			localeBasedInfoHTML += "</div>";
			localeBasedInfoHTML += "</td>";
			localeBasedInfoHTML += "</tr>";
		localeBasedInfoHTML += "<tr>";
			localeBasedInfoHTML += "<td width='150'>&nbsp;</td>";
			localeBasedInfoHTML += "<td width='475' colspan='2'><p class='basictext'>" + NewResolution.mediators[ID].getMediatorProfile() + "</p></td>";
			localeBasedInfoHTML += "</tr>";
			if (num < mediatorIDsForUniqueLocale[selectedlocalevalue].length) localeBasedInfoHTML += "<tr><td colspan='4'><HR align='left' size='1px' noshade color='#FF9900' class='formdivider4'></td></tr>";
			num += 1;
			}
		localeBasedInfoHTML += "</table>";
		showAll("holding_pen1");
		document.getElementById('holding_pen1').innerHTML = localeBasedInfoHTML;
		}
	else
		{
		showAll("instructions"); //If the user resumes the 'Select a Locale' setting on the locales drop-down menu, then show the div with id="instructions" again.
		}
	}
if (contactpageflag)
	{
	if (selectedlocalevalue != "")
		{
		showAll('holding_pen1');
		ShowMediatorInfo(selectedlocalevalue);
		}
	else
		{
		showAll("instructions"); //If the user resumes the 'Select a Locale' setting on the locales drop-down menu, then show the div with id="instructions" again.
		}
	}
if (feespageflag)
	{
	document.getElementById('meddropannex').innerHTML = RelateMediator(index);
	if (index != "") { if (mediatorIDsForUniqueLocale[index].length > 1) PresetMediatorsDropSelection(); }; // If RelateMediator called DisplayMediatorsForALocale (i.e. mediatorIDsForUniqueLocale[index].length > 1, and so the 'meddropannex' now contains a drop-down menu of mediators), preset mediators drop-down menu to value of the 'selectedmediator' cookie. Also use index != "" condition to avoid calling PresetMediatorsDropSelection() when index is "" i.e. the 'locales' drop-down menu is in its neutral position.
	}
return;
}


//Function that presets the selected item in the 'localesdrop' dropdown menu according to the value of the "selectedlocalelabel" cookie. This is a cousin function to PresetStatesDropSelection().
function PresetLocalesDropSelection()
{
var list = document.getElementById('localesdrop');
var counter;
var selectedlocalelabelvalue;
var valueoflocalelabelcookie;
// Test the cookie. If a cookie string exists AND that string includes a 'selectedlocale' cookie AND the value of the 'selectedlocale' cookie isn't "" (used by Firefox) AND the value of the 'selectedlocale' cookie isn't null (used by IE) then assign the 'selectedlocale' cookie's value to valueoflocalescookie; else, assign "" to  valueoflocalelabelcookie.
if (document.cookie && document.cookie.indexOf("selectedlocalelabel") > -1 && GetCookieValue("selectedlocalelabel") != "" && GetCookieValue("selectedlocalelabel") != null)
	{
	valueoflocalelabelcookie = GetCookieValue("selectedlocalelabel");
	}
else
	{
	valueoflocalelabelcookie = "";
	}
if (valueoflocalelabelcookie == "") 
	{ // Deals with case where the selection is 'Select a Locale'
	list.options[0].selected = true;
	selectedlocalelabelvalue = list.options[0].value; // i.e. sets selectedlocalelabelvalue to '' (empty)
	}
else
	{ // Deals with cases where the selection is one of the items in the uniqueLocaleLabel array.
	for (counter = 1; counter < list.options.length; counter++) // Compare the locale labels corresponding to the 2nd, 3rd, 4th, etc. index values in the localesdrop list (noting that the 1st option is the 'Select a Locale' of value "") with valueoflocalelabelcookie.
		{
		if (uniqueLocaleLabel[list.options[counter].value][0] == valueoflocalelabelcookie) 
			{
			list.options[counter].selected = true;
			selectedlocalelabelvalue = uniqueLocaleLabel[list.options[counter].value][1]; // Store in selectedlocalelabelvalue the index value from uniqueLocale that pertains to the selected option. The pertaining index value is stored in uniqueLocaleLabel[row][col=1]. This index value then gets sent as an argument for LocaleBasedInfoDumper, which in turn decides what gets shown and hidden among the 'instructions' div and the 'holding_pen1' div.
			break;
			}
		}
	// I think it's possible for the above 'for' loop to exhaust itself without finding a match between uniqueLocaleLabel[list.options[counter].value][0] and valueoflocalelabelcookie. I think such a scenario could occur if the user's browser has, say, a non-null valueoflocalelabelcookie that was set for, say, a demo mediator (e.g. "Miami-Fort Lauderdale-Pompano Beach_FL"). Unless that same locale label happened to also exist among the localesdrop drop-down menu list.options, a match won't be found and the loop would exit. In such a scenario, I think I need to reset the selectedlocalelabel cookie to null to help prevent a cookie conflict. I did notice errant behavior in IE (not in Firefox) that may have been caused by a scenario such as this. I can determine whether the loop ran through its full count (i.e. it wasn't broken out of via a break statement) by looking at the value of counter.
	if (counter = list.options.length) // i.e. we ran through the entire loop without finding a match
		{
		valueoflocalelabelcookie = "";
			
		}
	if (document.getElementById('localesdrop').value != '') LocaleBasedInfoDumper(selectedlocalelabelvalue); // Don't bother to call this if the localesdrop drop-down menu is in its neutral position.
	}
return;
}



//Function that presets the selected item in the 'mediatorsdrop' drop-down menu according to the value of the "selectedmediators" cookie. This is a cousin function to PresetLocalesDropSelection().
function PresetMediatorsDropSelection()
{
var list = document.getElementById('mediatorsforlocale');
var counter;
var selectedmediatorvalue;
var valueofmediatorscookie;
// Test the cookie. If a cookie string exists AND that string includes a 'selectedmediator' cookie AND the value of the 'selectedmediator' cookie isn't "" (used by Firefox) AND the value of the 'selectedmediator' cookie isn't null (used by IE) then assign the 'selectedmediator' cookie's value (i.e. a mediator's ID) to valueofmediatorscookie; else, assign "" to  valueofmediatorscookie.
if (document.cookie && document.cookie.indexOf("selectedmediator") > -1 && GetCookieValue("selectedmediator") != "" && GetCookieValue("selectedmediator") != null)
	{
	valueofmediatorscookie = GetCookieValue("selectedmediator");
	}
else
	{
	valueofmediatorscookie = "";
	}
if (valueofmediatorscookie == "") 
	{ // Deals with case where the selection is 'Select a Locale'
	list.options[0].selected = true;
	}
else
	{ // Deals with cases where the selection is one of the items in the 'mediatorsdrop' drop-down menu.
	for (counter = 1; counter < list.options.length; counter++) // Compare the mediators corresponding to the 2nd, 3rd, 4th, etc. index values in the mediatorsdrop list (noting that the 1st option is the 'Select a Mediator' of value "") with valueofmediatorscookie.
		{
		if (list.options[counter].value == valueofmediatorscookie) 
			{
			list.options[counter].selected = true;
			selectedmediatorvalue = list.options[counter].value; // Store the selected value in variable selectedmediatorvalue, which gets sent as an argument for DisplayFee, which in turn decides what gets shown and hidden among the 'instructions' div and the 'holding_pen1' div.
			if (locationsflag) document.getElementById('holding_pen2').innerHTML = RelateLocations(selectedmediatorvalue); // If the page is meant to show the selected mediator's locations (e.g. schedmediation.shtml), then fill holding_pen2 with those locations using the ID in the valueofmediatorscookie.
			break;
			}
		}
	}
if (feespageflag) 
	{
	if (document.cookie && document.cookie.indexOf("selectedmediator") > -1 && GetCookieValue("selectedmediator") != "" && GetCookieValue("selectedmediator") != null) { DisplayFee(selectedmediatorvalue); }
	}
return;
}

/* PrefillFormRecipient() takes the ID of the selected mediator in the mediators drop-down menu and calls GenerateFormRecipient(i) for that ID. I invoke (call) PrefillFormRecipient() on load of forms that show mediators in a drop-down menu i.e. c_schedmidationform.shtml, consultreqform.shtml, c_inpersonconsultreqform.shtml, and otherpartyrequestform.shtml (not c_contact.shtml). I need to call PrefillFormRecipient() b/c the form recipient fields that are placed inside the mediatoremailholder (and mediatornameholder) divs would otherwise be blank when the page is first loaded, and they'd remain blank until the user invoked the onchange method of the mediators drop-down menu. Yet that drop-down menu, being itself preset via cookies, might not need changing if the user feels happy with the mediator who is currently selected (i.e. preset). Hence my need to prefill those divs on page load. */
function PrefillFormRecipient()
{
var list = document.getElementById('mediatorsforlocale');
var selectedmediatorvalue;
selectedmediatorvalue = document.getElementById('mediatorsforlocale').value; // Assign selectedmediatorvalue to the value of the user-selected mediator in the mediatorsforlocale form element. The value will be the selected mediator's ID. (Note that if the selection is 'no mediator selected', the value is a null value of "").
GenerateFormRecipient(selectedmediatorvalue);
return;
}

/* Function that uses contents of uniqueLocale array to generate a drop-down list of unique locales. This is somewhat similar to function GenerateLocalesDrop(). (The only major differences are in the control flow within the onchange event handler.) GenerateUniqueLocaleDrop() creates a drop-down whose values are the 'uniqueLocaleLabel[][1]' (where this column element is actually the corresponding index from uniqueLocale[index]). Also note that GenerateLocalesDrop() is a sister function (i.e. similar) to GenerateStatesDrop(). GenerateLocalesDrop() gets used on pages such as s_fees.shtml, s_mediators.shtml, and c_contact.shtml whereas GenerateUniqueLocaleDrop() gets used on consultreqform.shtml, c_inpersonconsultreqform.shtml, otherpartyrequestform.shtml, and c_schedmediationform.shtml. */
function GenerateUniqueLocaleDrop()
{
// String together the HTML for the drop-down list using a for loop to process the unique locales in this select HTML element.
var uniqueLocaleDropHTML;
uniqueLocaleDropHTML = "<span class=\"basictextbold\">Your Locale:&nbsp;&nbsp;</span>";
uniqueLocaleDropHTML += "<select name='locale' id='locale' size='1' style='font-size: 12px; font-weight:normal; font-family:Arial,Helvetica,\'Century Gothic\', sans-serif' "
uniqueLocaleDropHTML += "onchange='showAll(\"holding_pen1\"); if (this.value == \"\") { SetCookie(\"selectedlocale\",\"\",\"\",\"\"); SetCookie(\"selectedlocalelabel\",\"\",\"\",\"\"); SetCookie(\"selectedmediator\",\"\",\"\",\"\"); SetCookie(\"selectedstate\",\"\",\"\",\"\"); hideAll(\"locationsdrop\"); hideAll(\"holding_pen1\"); PresetLocalesDrop(); } else { SetCookie(\"selectedlocale\",uniqueLocale[uniqueLocaleLabel[this.value][1]],\"\",\"\"); SetCookie(\"selectedlocalelabel\",uniqueLocaleLabel[this.value][0],\"\",\"\"); if (mediatorIDsForUniqueLocaleLabel[this.value].length == 1) SetCookie(\"selectedmediator\",mediatorIDsForUniqueLocaleLabel[this.value][0],\"\",\"\"); else SetCookie(\"selectedmediator\",\"\",\"\",\"\"); hideAll(\"locationsdrop\"); PresetLocalesDrop(); }'>";
uniqueLocaleDropHTML += "<option value=\"\" selected><&nbsp;Select a Locale&nbsp;></option>"; // When no locale is selected, the value is 'null' i.e. "".
var index, trunc;
for (index=0; index < uniqueLocaleLabel.length; index++)
	{
	if (uniqueLocaleLabelState[index] != "US") 
		{  
		// Generate the option element. Note use of the replace() method to convert from, say, 'Albuquerque_NM' to 'Albuquerque, NM' in the drop-down menu.
		uniqueLocaleDropHTML += "<option value=\"" + index + "\">" + uniqueLocaleLabel[index][0].replace('_', ', ') + "</option>";
		}
	else
		{
		trunc = uniqueLocaleLabel[index][0].split('_'); trunc = trunc[0];
		uniqueLocaleDropHTML += "<option value=\"" + index + "\">" + trunc + "</option>";
		}
	}
uniqueLocaleDropHTML += "</select>";
uniqueLocaleDropHTML += "<span class=\"tangsup\">&nbsp;&nbsp;<b>*</b></span>";
return uniqueLocaleDropHTML;
}


/*
Function used to preset the locales drop-down menus (on pages such as consultreqform.shtml, c_inpersonconsultreqform.shtml, c_schedmediationform.shtml, otherpartyrequestform.shtml) to the value of the 'selectedlocalelabel' cookie (if it has been set to a value).
*/
function PresetLocalesDrop()
{
var list = document.getElementById('locale'); 
var valueoflocalelabelcookie;
var form;
// Test the cookie. If a cookie string exists AND that string includes a 'selectedlocale' cookie AND the value of the 'selectedlocale' cookie isn't "" (used by Firefox) AND the value of the 'selectedlocale' cookie isn't null (used by IE) then assign the 'selectedlocalelabel' cookie's value to valueoflocalelabelcookie; else, assign "" to  valueoflocalelabelcookie.
if (document.cookie && document.cookie.indexOf("selectedlocale") > -1 && GetCookieValue("selectedlocale") != "" && GetCookieValue("selectedlocale") != null)
	{
	valueoflocalelabelcookie = GetCookieValue("selectedlocalelabel");
	}
else
	{
	valueoflocalelabelcookie = "";
	}
// Next do a pattern match via a for loop to discover which option in the locales drop-down list corresponds to the value of the valueoflocalelabelcookie variable.
if (valueoflocalelabelcookie == "") 
	{ // Deals with case where the selection is 'Select a Locale'
	list.options[0].selected = true;
	}
else
	{ // Deals with cases where the selection is one of the items in the uniqueLocaleLabel array.
	for (counter = 1; counter < list.options.length; counter++) // Compare the locale labels corresponding to the 2nd, 3rd, 4th, etc. index values in the "locales" drop-down list (noting that the 1st option is the 'Select a Locale' of value "") with valueoflocalelabelcookie.
		{
		if (uniqueLocaleLabel[list.options[counter].value][0] == valueoflocalelabelcookie) 
			{
			list.options[counter].selected = true;
			hideAll("locationsdrop");
			document.getElementById("holding_pen1").innerHTML = RelateMediator(uniqueLocaleLabel[counter-1][1]); // The second [1th] column of the (counter-1)th row in the uniqueLocaleLabel 2-D array contains the index of the uniqueLocale array that should be given as the parameter for RelateMediator.
			if (mediatorIDsForUniqueLocale[uniqueLocaleLabel[counter-1][1]].length > 1) PresetMediatorsDropSelection(); // Also preset the mediators drop-down menu if one exists on the page i.e. if the number of IDs for the associated unique locale is > 1.
			break;
			}
		}
	}
return;
}


// RelateMediator() is a traffic-cop function that relates mediator or mediators to the relevant index of the locale. (This locale index pertains to the locale label selected by the user.)
function RelateMediator(index)
{
	var index, ID;
	var relateMediatorHTML;
	switch (index) // Use switch to control hiding of the mediator (or mediator drop-down) when user reverts to 'no locale selected' on locale drop-down
	{
	case "": // set relateMediatorHTML to an empty string when user reverts to 'no locale selected' (i.e. the case of null value, "") on locale drop-down
		if (feespageflag) showAll('instructions');
		relateMediatorHTML = "";
		return relateMediatorHTML;
	default: // In all others cases, either set relateMediatorHTML to a mediator drop-down (when more than one mediator exists for the selected locale) or set relateMediatorHTML to combine the only mediator for that locale together with that mediator's location or fee information.
	if (mediatorIDsForUniqueLocale[index].length > 1) // Executed if there is more than one mediator associated with the user-selected locale
		{
		relateMediatorHTML = DisplayMediatorsForALocale(index);
		return relateMediatorHTML;
		}
	else // Executed if there's just one mediator for the user-selected locale
		{
		ID = mediatorIDsForUniqueLocale[index]; // Get the ID of the single mediator for this locale by assigning the contents of mediatorIDsForUniqueLocale[index] to ID. The mediatorIDsForUniqueLocale[i][column] should contain just a single ID (i.e. one column) in situations where there's just one mediator for the user-selected locale.
		if (feespageflag)
			{
			DisplayFee(ID);
			relateMediatorHTML = ""; // On fees page, place nothing in the meddropannex div i.e. no need for a drop-down menu of mediators for the selected locale because there is only one mediator in this locale.
			return relateMediatorHTML;
			}
		else
			{
			relateMediatorHTML = DisplayMediator(ID);
			}
		if (locationsflag == true) relateMediatorHTML += DisplayLocationsForAMediator(ID); // Only append locations if locationsflag is set to true
		return relateMediatorHTML;
		}
	}
}


//Function that displays a drop-down menu of those mediator(s) who all share the common locale of index = i within uniqueLocale[i].
// Note that this function uses the fact that mediatorIDsForUniqueLocale[i] is a 2D array that contains the IDs of those mediators who have the common locale of uniqueLocale[i]
// Note also: we call GenerateFormRecipient(i); on change of the mediators drop-down menu to fill the div mediatoremailholder with the email address of the mediator for use as the value of the form's recipient hidden field
function DisplayMediatorsForALocale(i)
{
// String together the HTML for the drop-down list of the multiple mediators who have the common locale
// Note: we only call RelateLocations on change of the mediators drop-down if the locationsflag is set to true
mediatorsForThisLocaleDropHTML = "";
if (feespageflag) mediatorsForThisLocaleDropHTML += "<br/>"
mediatorsForThisLocaleDropHTML += "<span class=\"basictextbold\">Your Mediator:&nbsp;&nbsp;</span>";
mediatorsForThisLocaleDropHTML += "<select name=\"mediatorsforlocale\" id='mediatorsforlocale' size=\"1\" style=\"font-size: 12px; font-weight:normal; font-family:Arial,Helvetica,'Century Gothic', sans-serif\" onChange='SetCookie(\"selectedmediator\",this.value,\"\",\"\"); if (this.value != \"\") SetCookie(\"selectedlocalelabel\",NewResolution.mediators[this.value].getMediatorLocaleLabel() + \"_\" + NewResolution.mediators[this.value].getMediatorState(),\"\",\"\"); if (!feespageflag) { hideAll(\"locationsdrop\"); FillAboutMediatorsHolder(this.value); if (this.value != \"\") GenerateFormRecipient(this.form.mediatorsforlocale.value); PresetLocalesDrop(); } else { DisplayFee(this.value); }'>";
mediatorsForThisLocaleDropHTML += "<option value=\"\" selected><&nbsp;Select a Mediator&nbsp;></option>"; // Initially, the mediator drop down has a null (i.e. "") value
var count, temp;
//var list = document.getElementById('mediatorsforlocale'); // Unnecessary line!
for (count=0; count < mediatorIDsForUniqueLocale[i].length; count++)
	{
	temp = mediatorIDsForUniqueLocale[i][count]; // temp holds the first ID, then the second ID, then the third ID, etc. element of mediatorIDsForUniqueLocale[i][] array as we progress through the count loop.
	mediatorsForThisLocaleDropHTML += "<option value=\""; 
	mediatorsForThisLocaleDropHTML += NewResolution.mediators[temp].getMediatorID(); // Note: temp should equal the mediator's ID at each iteration through the count loop
	mediatorsForThisLocaleDropHTML += "\">";
	mediatorsForThisLocaleDropHTML += NewResolution.mediators[temp].getMediatorName();
	mediatorsForThisLocaleDropHTML += "</option>";
	}
mediatorsForThisLocaleDropHTML += "</select>";
if (!feespageflag) 
	{
	mediatorsForThisLocaleDropHTML += "<span class=\"tangsup\">&nbsp;&nbsp;<b>*</b></span>";
	if (document.cookie && document.cookie.indexOf('selectedmediator') > -1 && GetCookieValue('selectedmediator') != "" && GetCookieValue('selectedmediator') != null) 
	{
	mediatorsForThisLocaleDropHTML += "&nbsp;&nbsp;&nbsp;<span id='aboutmediatorholder'><a href='s_mediators.shtml#med" + GetCookieValue('selectedmediator') + "' onClick=\"wintasticsecond('s_mediators.shtml#med" + GetCookieValue('selectedmediator') + "'); return false;\">[About&nbsp;" + NewResolution.mediators[GetCookieValue('selectedmediator')].getMediatorName() + "]</a></span>";
	}
	else 
	{
	mediatorsForThisLocaleDropHTML += "&nbsp;&nbsp;&nbsp;<span id='aboutmediatorholder'><a href='s_mediators.shtml' onClick=\"wintasticsecond('s_mediators.shtml'); return false;\">[About Our Mediators]</a></span>";
	};
	mediatorsForThisLocaleDropHTML += "<HR noshade color=\"#FF9900\" size=\"1px\" class=\"formdivider3noleftmargin\" style=\"margin-left: 34px\">";
	}
return mediatorsForThisLocaleDropHTML;
}

// Function to fill the span id='aboutmediatorholder' with either '[About Our Mediators]' or '[About Name of Mediator]' on change of the mediatorsforlocale drop-down menu. FillAboutMediatorsHolder(i) is called by DisplayMediatorsForALocale(i). Note: this function only needs to deal with situations where the selected locale has > 1 mediator because situations in which the selectedlocale has just one mediator are dealt with inside DisplayMediator(i).
function FillAboutMediatorsHolder(i)
{
var i;
if (i == "" || i == null) document.getElementById('aboutmediatorholder').innerHTML = "<a href='s_mediators.shtml' onclick=\"wintasticsecond(\'s_mediators.shtml'); return false;\">[About Our Mediators]</a>";
else document.getElementById('aboutmediatorholder').innerHTML = "<a href='s_mediators.shtml#med" + GetCookieValue('selectedmediator') + "' onClick=\"wintasticsecond('s_mediators.shtml#med" + GetCookieValue('selectedmediator') + "'); return false;\">[About&nbsp;" + NewResolution.mediators[i].getMediatorName() + "]</a>";
return;
}

function DisplayMediator(i)
{
	var i;
	var selectedMediatorHTML;
		if (!feespageflag) GenerateFormRecipient(i); // First call this function to fill the div mediatoremailholder with the email address of the mediator for use as the value of the form's recipient hidden field. But don't bother if executing DisplayMediator for the fees page, which doesn't require determination of a mediator email address.
		// Now generate the HTML code for displaying the name of the only mediator for the user-selected locale.
		selectedMediatorHTML = "<span class=\"basictextbold\">Your mediator is&nbsp;" + NewResolution.mediators[i].getMediatorName() + "</span>";
		if (!feespageflag) selectedMediatorHTML += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='s_mediators.shtml' onClick=\"wintasticsecond('s_mediators.shtml'); return false;\">[About&nbsp;" + NewResolution.mediators[i].getMediatorName() + "]</a>";
		if (!feespageflag) selectedMediatorHTML += "<HR noshade color=\"#FF9900\" size=\"1px\" class=\"formdivider2noleftmargin\" style=\"margin-left: 34px\">";
		return selectedMediatorHTML;
}

// RelateLocations(i) is a traffic-cop function that relates a mediator's locations to the mediator selected by the user in cases where the user-selected locale has more than one mediator.
// Note: In those other cases where the user-selected locale has just one mediator, we were able to call DisplayLocationsForAMediator(i) directly from inside RelateMediator(form) without needing this RelateLocations(i) traffic-cop function.
function RelateLocations(i)
{
	var i, relateLocationsHTML;
	switch(i)  // Use to control hiding of the locations drop-down inside the holding_pen2 div when user reverts to 'no mediator selected' on the mediatorsforlocale mediators drop-down
	{
		case "": // set relateLocationsHTML to an empty string in the case of the user reverting to 'no mediator selected' (i.e. the null value of "") on the mediatorsforlocale mediators drop-down
		{
			relateLocationsHTML = "";
			return relateLocationsHTML;
		}
		default:
		{
			relateLocationsHTML = DisplayLocationsForAMediator(i);
		}
	}
	return relateLocationsHTML;
}


function DisplayLocationsForAMediator(i)
{
	var i;
	var locationsForThisMediatorDropHTML;
	var counter, temp;
locationsForThisMediatorDropHTML = "<div id=\"locationsdrop\">";
locationsForThisMediatorDropHTML += "<table style='cellspacing: 0px; cellpadding: 0px; width: 500px'><tr><td width='500px'>";
locationsForThisMediatorDropHTML += "<span class=\"basictextbold\">Location:&nbsp;&nbsp;</span>";
locationsForThisMediatorDropHTML += "<select name=\"first_location\" size=\"1\" style=\"font-size: 12px; font-weight:normal; font-family:Arial,Helvetica,'Century Gothic', sans-serif\">";
locationsForThisMediatorDropHTML += "<option value=\"no_first_location_selected\" selected><&nbsp;Select First Choice&nbsp;></option>";
for (counter in NewResolution.mediators[i].getMediatorLocations())
	{
	locationsForThisMediatorDropHTML += "<option value=\"";
	locationsForThisMediatorDropHTML +=  NewResolution.mediators[i].getMediatorLocations()[counter];
	locationsForThisMediatorDropHTML += "\">";
	locationsForThisMediatorDropHTML += NewResolution.mediators[i].getMediatorLocations()[counter];
	locationsForThisMediatorDropHTML += "</option>";
	}
locationsForThisMediatorDropHTML += "</select>";
locationsForThisMediatorDropHTML += "&nbsp;<span class=\"tangsup\"><b>*</b></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
locationsForThisMediatorDropHTML += "<select name='second_location' size='1' style='font-size: 12px; font-weight:normal; font-family:Arial,Helvetica,\'Century Gothic\', sans-serif;'>";
locationsForThisMediatorDropHTML += "<option value=\"no_second_location_selected\" selected><&nbsp;Select Second Choice&nbsp;></option>";
for (counter in NewResolution.mediators[i].getMediatorLocations())
	{
	locationsForThisMediatorDropHTML += "<option value=\"";
	locationsForThisMediatorDropHTML +=  NewResolution.mediators[i].getMediatorLocations()[counter];
	locationsForThisMediatorDropHTML += "\">";
	locationsForThisMediatorDropHTML += NewResolution.mediators[i].getMediatorLocations()[counter];
	locationsForThisMediatorDropHTML += "</option>";
	}
locationsForThisMediatorDropHTML += "</select>";
locationsForThisMediatorDropHTML +=	"</td></tr></table>";
locationsForThisMediatorDropHTML += "<HR noshade color=\"#FF9900\" size=\"1px\" class=\"formdivider3noleftmargin\" style=\"margin-left: 34px\">";
locationsForThisMediatorDropHTML += "</div>";
return locationsForThisMediatorDropHTML;
}

function GenerateFormRecipient(i)
// String together the HTML for the hidden form element of name = "recipients" whose value is the email address of the person who receives the form data i.e. the email address of the selected mediator.
{
	var selectedMediatorEmailHTML, i;
	selectedMediatorEmailHTML = "<input type=hidden name=\"recipients\" value=\"";
	selectedMediatorEmailHTML += NewResolution.mediators[i].getMediatorEmail();
	selectedMediatorEmailHTML += "\">";
	document.getElementById('mediatoremailholder').innerHTML = selectedMediatorEmailHTML;
// Also establish a hidden form element of name = "selectedmediator" whose value is the name of the user-selected mediator. I need to define this element because I include <<selectedmediator>> in the email template (e.g. file = inpersonconsultsubmit.txt for the in-person consultation request form) that goes to the mediator giving him/her details of the inquiry.
	var selectedMediatorNameForFormHTML;
	selectedMediatorNameForFormHTML = "<input type=hidden name=\"selectedmediator\" value=\"";
	selectedMediatorNameForFormHTML += NewResolution.mediators[i].getMediatorName();
	selectedMediatorNameForFormHTML += "\">";
	document.getElementById('mediatornameholder').innerHTML = selectedMediatorNameForFormHTML;
return;	
}

function GenerateFormRecipients(selectedStatuses)
// Unlike the similarly named and simpler GenerateFormRecipient(), which sends form data to a single recipient, GenerateFormRecipients() can handle multiple recipients. GenerateFormRecipients() is called inside ShowMediatorInfo(). The recipients are determined by the mediator(s) for whom the user checked their checkboxes. Like GenerateFormRecipient(), GenerateFormRecipients() strings together the HTML for the hidden form element of name = "recipients" (sic. NOTE: formmail.php uses 'recipients' whereas FormHandler.cgi uses 'recipient' as its field name) whose value is the email address(es) of the mediator(s) who should receives the form data i.e. the email address of the selected mediator(s).
{
	var selectedMediatorEmailHTML, counter, selectedStatuses;
	var IDsStringArray = new Array(); // This is used to hold the IDs of mediators whose checkboxes have been selected i.e. it holds the index value of selectedStatuses when selectedStatuses[index] is true.
	var emailsStringArray = new Array; // A "parallel" of the IDsStringArray array, the emailsStringArray array holds the email addresses of mediators whose checkboxes have been selected.
	var emailsString;
	IDsStringArray = []; emailsStringArray = []; // Clean (i.e. set or reset to empty) these two arrays each time the GenerateFormRecipients function is called i.e. each time one of the checkboxes on, say, the c_contact.shtml page is clicked. 
	selectedMediatorEmailHTML = "<input type=\"hidden\" name='recipients' value='";
	for (counter in selectedStatuses)
	{
		if (!selectedStatuses[counter]) 
		delete selectedStatuses[counter]; // Delete any false values from the selectedStatuses array.
		else 
			{
			IDsStringArray.push(counter); // Else populate array IDsStringArray with the ID of each mediator who had a 'true' status...
			emailsStringArray.push(NewResolution.mediators[counter].getMediatorEmail()); // ... and populate the emailsStringArray array with the email address that corresponds to that ID (i.e. the current index value, counter).
			}
	}
	emailsString = emailsStringArray.join(",");  // Use of this join method assigns to emailsString a comma-separated values version of emailsStringArray, which is automatically converted by this method into a string type.
	selectedMediatorEmailHTML += emailsString;
	selectedMediatorEmailHTML += "'>";
	document.getElementById('mediatoremailholder').innerHTML = selectedMediatorEmailHTML;
/* I'm temporarily, at least, abandoning this section -- too complex to include selectedmediator when mailing to multiple mediators?
// Also establish a hidden form element of name = "selectedmediator" whose value is the name of the user-selected mediator. I need to define this element because I include <<selectedmediator>> in the email template (e.g. file = inpersonconsultsubmit.txt for the in-person consultation request form) that goes to the mediator giving him/her details of the inquiry. However, c_contact.shtml, which has potentially multiple mediator names per email, now uses formmail.php, which has a different convention (it uses the $ symbol) for including field values anyway.
	var selectedMediatorNameForFormHTML;
	selectedMediatorNameForFormHTML = "<input type=hidden name=\"selectedmediator\" value=\"";
	selectedMediatorNameForFormHTML += NewResolution.mediators[i].getMediatorName();
	selectedMediatorNameForFormHTML += "\">";
	document.getElementById('mediatornameholder').innerHTML = selectedMediatorNameForFormHTML;
*/

return;	
}

/*
This function generates the HTMLfor a mediator's fee information. It is called onchange of the mediators' drop-down menu within DisplayMediatorsForALocale().
*/
function DisplayFee(ID)
{
// This first block of codes determines whether the locale pertaining to the ID has just one mediator or whether more than one ID (i.e. more than one mediator) has that locale. Normally, I could just look at the length of the 2-D array mediatorIDForUniqueLocale[index], but DisplayFee(ID) doesn't pass the index parameter, so I need to use this roundabout method instead!
	var solo = true; // Initially assume there's just one mediator ID for the ID's locale.
	var count = 0;
	var i;
	var hrs, mins, totmins; // Used in calculation of total duration (hours and minutes) of each package.
	var pkgcost, equivcost, percentdiscount; // Used in calculation of discount savings for each package compared to regular hrly rate.
// Now the main part of the DisplayFee(ID) function:
	if (ID != "")
		{
			var loc = NewResolution.mediators[ID].getMediatorLocale();
			for (i in mediatorLocale)
			{
				if (loc == mediatorLocale[i]) count += 1;
				if (count > 1) { solo = false; break; }
			}
			mediatorFeeHTML = "<h2>" + NewResolution.mediators[ID].getMediatorName();
			if (NewResolution.mediators[ID].getMediatorCred() != '') { mediatorFeeHTML += ", " + NewResolution.mediators[ID].getMediatorCred() }; // Only append a mediator's credential if he/she has one.
			mediatorFeeHTML += "</h2>";
			mediatorFeeHTML += "<h4>Consultations</h4>";
			cnsltPcy = NewResolution.mediators[ID].getMediatorConsultationPolicy();
			if (cnsltPcy[0] && cnsltPcy[1]) // Free telephone and in-person consultations offered.
				{
				mediatorFeeHTML += "<p class='text'>Free <a href='consultreqform.shtml'>telephone</a> and free <a href='c_inpersonconsultreqform.shtml'>in-person</a> consultations are available.";
				if (cnsltPcy[2]) mediatorFeeHTML += "&nbsp;A charge may apply for in-person consultations at a satellite location.";
				}
			else if (cnsltPcy[0]) // A fee applies for in-person consultations only.
				{
				mediatorFeeHTML += "<p class='text'>Free <a href='consultreqform.shtml'>telephone consultations</a> are available. A fee applies for <a href='c_inpersonconsultreqform.shtml'>in-person</a>&nbsp;consult&shy;ations.";
				if (cnsltPcy[2]) mediatorFeeHTML += "&nbsp;A location charge may also apply.";
				}
			else if (cnsltPcy[1]) // A fee applies for telephone consultations only. Very improbable clause.
				{
				mediatorFeeHTML += "<p class='text'>Free in-person consultations are available. Telephone consultations are not available.";
				if (cnsltPcy[2]) mediatorFeeHTML += " A location charge may apply for use of a satellite location.";
				}
			else // Neither telephone nor in-person consultations are free.
				{
				mediatorFeeHTML += "<p class='text'>In-person and telephone consultations are available on request. A fee may apply.";
				}
			if ((!cnsltPcy[0] || !cnsltPcy[1]) && cnsltPcy[3]) mediatorFeeHTML += "&nbsp;" + cnsltPcy[4] + "% of the consultation fee is refundable as a credit towards your first mediation session.";
			mediatorFeeHTML += " <a href='c_contact.shtml";
			if (!solo) mediatorFeeHTML += "#med" + ID; // Append the internal hyperlink anchor if there will be more than one mediator listed on the destination page.
			mediatorFeeHTML += "'>Contact</a> " + NewResolution.mediators[ID].getMediatorName() + " for more details.</p>";
			if (NewResolution.mediators[ID].getMediatorPackages()[1] != '' || NewResolution.mediators[ID].getMediatorPackages()[3] != '' || NewResolution.mediators[ID].getMediatorPackages()[5] != '') { mediatorFeeHTML += "<h4>Mediation: Hourly Rate Plan</h4>"; } else { mediatorFeeHTML += "<h4>Mediation Sessions</h4>"; } // If no packages are offered then simplify title from 'Mediation: Hourly Rate Plan' to just 'Mediation'.
			if (NewResolution.mediators[ID].getMediatorHourlyRate()[0]) // if the mediatorHourlyRate[0] array has a 'true' value for the mediator with this ID, then display the hourly rate and related data.
				{
				hrly = NewResolution.mediators[ID].getMediatorHourlyRate()[1]; // mediator's hourly rate
				hrlyHalf = hrly/2;
				if (IsInteger(hrlyHalf) == false) { hrlyHalf = hrlyHalf.toFixed(2) } // If the computation of hrly / 2 yields a fractional result (e.g. 325/2 = 162.5), then use Number.toFixed() method to two decimal places.
				mediatorFeeHTML += "<p class='text'>$" + hrly + " per hour ($" + hrlyHalf + " per party per hour for two-party disputes)&nbsp;<sup>&dagger;</sup></p>";
				mediatorFeeHTML += "<p class='textsmallerhangindent'>&dagger;&nbsp;&nbsp;Fees are assessed in " + NewResolution.mediators[ID].getMediatorIncrement() + "-minute increments.</p>";
				mediatorFeeHTML += "<p class='textsmallerhangindent'>&dagger;&nbsp;&nbsp;Parties may cancel up to " + NewResolution.mediators[ID].getMediatorCancellationPolicy()[0] + "&nbsp;";
				if (NewResolution.mediators[ID].getMediatorCancellationPolicy()[1] == "week(s)")
					{
						if (NewResolution.mediators[ID].getMediatorCancellationPolicy()[0] > 1) 
							{ mediatorFeeHTML += "weeks"; }
						else 
							{ mediatorFeeHTML += "week"; }
					}
				else
					{
					mediatorFeeHTML += NewResolution.mediators[ID].getMediatorCancellationPolicy()[1];
					}
				mediatorFeeHTML += " before a scheduled session. Cancellations within " + NewResolution.mediators[ID].getMediatorCancellationPolicy()[0] + "&nbsp;";
				if (NewResolution.mediators[ID].getMediatorCancellationPolicy()[1] == "week(s)")
					{
						if (NewResolution.mediators[ID].getMediatorCancellationPolicy()[0] > 1) 
							{ mediatorFeeHTML += "weeks"; }
						else 
							{ mediatorFeeHTML += "week"; }
					}
				else
					{
					mediatorFeeHTML += NewResolution.mediators[ID].getMediatorCancellationPolicy()[1];
					}
				mediatorFeeHTML += " incur a fee of $" + NewResolution.mediators[ID].getMediatorCancellationPolicy()[2] + ".</p>";
				if (NewResolution.mediators[ID].getMediatorTelephoneMediations() || NewResolution.mediators[ID].getMediatorVideoConf())
				{
					mediatorFeeHTML += "<p class='textsmallerhangindent'>&dagger;&nbsp;&nbsp;";
					if (NewResolution.mediators[ID].getMediatorTelephoneMediations()) mediatorFeeHTML += "Telephone mediations are available. ";
					if (NewResolution.mediators[ID].getMediatorVideoConf()) mediatorFeeHTML += "Video-conferencing (e.g. Skype) is also available.";
					mediatorFeeHTML += "</p>";
				}
				if (NewResolution.mediators[ID].getMediatorAdminCharge()) // Mediator does charge an Admin Charge.
				{
					if (NewResolution.mediators[ID].getMediatorAdminChargeDetails()[0]) // Either: mediator publishes his/her Admin Charge ...
						{
						mediatorFeeHTML += "<p class='textsmallerhangindent'>&dagger;&nbsp;&nbsp;A $" + NewResolution.mediators[ID].getMediatorAdminChargeDetails()[1] + " case administration charge applies.</p>";
						}
					else // ... Or: mediator doesn't publish his/her Admin Charge
						{
						mediatorFeeHTML += "<p class='textsmallerhangindent'>&dagger;&nbsp;&nbsp;A case administration charge may apply.</p>";
						}
				}
				if (NewResolution.mediators[ID].getMediatorSlidingScale()) mediatorFeeHTML += "<p class='textsmallerhangindent'>&dagger;&nbsp;&nbsp;Sliding-scale discounts may be available.</p>";
				}
			else
				{
				mediatorFeeHTML += "<p class='text'><a href='c_contact.shtml";
				if (!solo) mediatorFeeHTML += "#med" + ID; // Append the internal hyperlink anchor if there will be more than one mediator listed on the destination page.
				mediatorFeeHTML += "'>Contact</a> " + NewResolution.mediators[ID].getMediatorName() + " for details.</p>";
				}
			if (NewResolution.mediators[ID].getMediatorPackages()[0])  // Display details of up to three packages if this first column element from the mediatorPackages 2-D array[ID][col] is true.
				{
				mediatorFeeHTML += "<h4>Mediation: Package Plans</h4>";
				mediatorFeeHTML += "<p class='text'>";
				if (NewResolution.mediators[ID].getMediatorPackages()[1] != "") 
					{
					mediatorFeeHTML += NewResolution.mediators[ID].getMediatorPackages()[1] + "-Session Package (";
					totmins = NewResolution.mediators[ID].getMediatorPackages()[1] * (NewResolution.mediators[ID].getMediatorPackages()[7] * 60 + NewResolution.mediators[ID].getMediatorPackages()[8]); // Total duration of this package in minutes.
					hrs = Math.floor(totmins/60); // Total number of hours for this package.
					mins = totmins%60; // Number of minutes (i.e. modulus or remainder function) for package.
					mediatorFeeHTML += hrs + " hrs";
					if (mins > 0) mediatorFeeHTML += " " + mins + " mins";
					mediatorFeeHTML += "): $" + NewResolution.mediators[ID].getMediatorPackages()[2] + "&nbsp;<sup>&Dagger;</sup>";
					if (NewResolution.mediators[ID].getMediatorHourlyRate()[0]) // If the mediator has chosen to publish his or her hourly rate, we can also include the discount savings next to each package.
						{
						pkgcost = NewResolution.mediators[ID].getMediatorPackages()[2];
						equivcost = (totmins/60) * NewResolution.mediators[ID].getMediatorHourlyRate()[1]; // Calculate how much this package would have cost at the regular hourly rate.
						equivcost = Math.round(equivcost);
						percentdiscount = (equivcost - pkgcost)/equivcost * 100;
						percentdiscount = Math.round(percentdiscount);
						mediatorFeeHTML += "&nbsp;&nbsp;&nbsp;{Savings on hourly rate plan: " + percentdiscount + "%}";
						}
					mediatorFeeHTML += "<br>";
					}
				if (NewResolution.mediators[ID].getMediatorPackages()[3] != "") 
					{
					mediatorFeeHTML += NewResolution.mediators[ID].getMediatorPackages()[3] + "-Session Package (";
					totmins = NewResolution.mediators[ID].getMediatorPackages()[3] * (NewResolution.mediators[ID].getMediatorPackages()[7] * 60 + NewResolution.mediators[ID].getMediatorPackages()[8]); // Total duration of this package in minutes.
					hrs = Math.floor(totmins/60); // Total number of hours for this package.
					mins = totmins%60; // Number of minutes (i.e. modulus or remainder function) for package.
					mediatorFeeHTML += hrs + " hrs";
					if (mins > 0) mediatorFeeHTML += " " + mins + " mins";
					mediatorFeeHTML += "): $" + NewResolution.mediators[ID].getMediatorPackages()[4] + "&nbsp;<sup>&Dagger;</sup>";
					if (NewResolution.mediators[ID].getMediatorHourlyRate()[0]) // If the mediator has chosen to publish his or her hourly rate, we can also include the discount savings next to each package.
						{
						pkgcost = NewResolution.mediators[ID].getMediatorPackages()[4];
						equivcost = (totmins/60) * NewResolution.mediators[ID].getMediatorHourlyRate()[1]; // Calculate how much this package would have cost at the regular hourly rate.
						equivcost = Math.round(equivcost);
						percentdiscount = (equivcost - pkgcost)/equivcost * 100;
						percentdiscount = Math.round(percentdiscount);
						mediatorFeeHTML += "&nbsp;&nbsp;&nbsp;{Savings on hourly rate plan: " + percentdiscount + "%}";
						}
					mediatorFeeHTML += "<br>";
					}
				if (NewResolution.mediators[ID].getMediatorPackages()[5] != "") 
					{
					mediatorFeeHTML += NewResolution.mediators[ID].getMediatorPackages()[5] + "-Session Package (";
					totmins = NewResolution.mediators[ID].getMediatorPackages()[5] * (NewResolution.mediators[ID].getMediatorPackages()[7] * 60 + NewResolution.mediators[ID].getMediatorPackages()[8]); // Total duration of this package in minutes.
					hrs = Math.floor(totmins/60); // Total number of hours for this package.
					mins = totmins%60; // Number of minutes (i.e. modulus or remainder function) for package.
					mediatorFeeHTML += hrs + " hrs";
					if (mins > 0) mediatorFeeHTML += " " + mins + " mins";
					mediatorFeeHTML += "): $" + NewResolution.mediators[ID].getMediatorPackages()[6] + "&nbsp;<sup>&Dagger;</sup>";
					if (NewResolution.mediators[ID].getMediatorHourlyRate()[0]) // If the mediator has chosen to publish his or her hourly rate, we can also include the discount savings next to each package.
						{
						pkgcost = NewResolution.mediators[ID].getMediatorPackages()[6];
						equivcost = (totmins/60) * NewResolution.mediators[ID].getMediatorHourlyRate()[1]; // Calculate how much this package would have cost at the regular hourly rate.
						equivcost = Math.round(equivcost);
						percentdiscount = (equivcost - pkgcost)/equivcost * 100;
						percentdiscount = Math.round(percentdiscount);
						mediatorFeeHTML += "&nbsp;&nbsp;&nbsp;{Savings on hourly rate plan: " + percentdiscount + "%}";
						}
					mediatorFeeHTML += "<br>";
					}
				mediatorFeeHTML += "<p class='textsmallerhangindent'>&Dagger;&nbsp;&nbsp;Each package session is typically " + NewResolution.mediators[ID].getMediatorPackages()[7] + " hours"; // Show number of hours in each session of a package.
				if (NewResolution.mediators[ID].getMediatorPackages()[8] > 0) mediatorFeeHTML += " " + NewResolution.mediators[ID].getMediatorPackages()[8] + " minutes"; // Include minutes too if they are non-zero.
				mediatorFeeHTML +=".</p>";
				mediatorFeeHTML += "<p class='textsmallerhangindent'>&Dagger;&nbsp;&nbsp;Parties may cancel up to " + NewResolution.mediators[ID].getMediatorCancellationPolicy()[0] + "&nbsp;";
				if (NewResolution.mediators[ID].getMediatorCancellationPolicy()[1] == "week(s)")
					{
						if (NewResolution.mediators[ID].getMediatorCancellationPolicy()[0] > 1) 
							{ mediatorFeeHTML += "weeks"; }
						else 
							{ mediatorFeeHTML += "week"; }
					}
				else
					{
					mediatorFeeHTML += NewResolution.mediators[ID].getMediatorCancellationPolicy()[1];
					}
				mediatorFeeHTML += " before a scheduled session. Cancellations within " + NewResolution.mediators[ID].getMediatorCancellationPolicy()[0] + "&nbsp;";
				if (NewResolution.mediators[ID].getMediatorCancellationPolicy()[1] == "week(s)")
					{
						if (NewResolution.mediators[ID].getMediatorCancellationPolicy()[0] > 1) 
							{ mediatorFeeHTML += "weeks"; }
						else 
							{ mediatorFeeHTML += "week"; }
					}
				else
					{
					mediatorFeeHTML += NewResolution.mediators[ID].getMediatorCancellationPolicy()[1];
					}
				mediatorFeeHTML += " incur a fee of $" + NewResolution.mediators[ID].getMediatorCancellationPolicy()[2] + ".</p>";
				if (NewResolution.mediators[ID].getMediatorTelephoneMediations() || NewResolution.mediators[ID].getMediatorVideoConf())
				{
					mediatorFeeHTML += "<p class='textsmallerhangindent'>&Dagger;&nbsp;&nbsp;";
					if (NewResolution.mediators[ID].getMediatorTelephoneMediations()) mediatorFeeHTML += "Telephone mediations are available. ";
					if (NewResolution.mediators[ID].getMediatorVideoConf()) mediatorFeeHTML += "Video-conferencing (e.g. Skype) is also available.";
					mediatorFeeHTML += "</p>";
				}
				if (NewResolution.mediators[ID].getMediatorAdminCharge()) // Mediator does charge an Admin Charge.
				{
					if (NewResolution.mediators[ID].getMediatorAdminChargeDetails()[0]) // Either: mediator publishes his/her Admin Charge ...
						{
						mediatorFeeHTML += "<p class='textsmallerhangindent'>&Dagger;&nbsp;&nbsp;A $" + NewResolution.mediators[ID].getMediatorAdminChargeDetails()[1] + " case administration charge applies.</p>";
						}
					else // ... Or: mediator doesn't publish his/her Admin Charge
						{
						mediatorFeeHTML += "<p class='textsmallerhangindent'>&Dagger;&nbsp;&nbsp;A case administration charge may apply.</p>";
						}
				}
			if (NewResolution.mediators[ID].getMediatorSlidingScale()) mediatorFeeHTML += "<p class='textsmallerhangindent'>&Dagger;&nbsp;&nbsp;Sliding-scale discounts may be available.</p>";
				}
			if (NewResolution.mediators[ID].getMediatorLocationCharge()[0])  // Display details of location charges if this first column element from the mediatorLocationCharge 2-D array[ID][col] is true.
				{
				mediatorFeeHTML += "<h4>Supplemental Location Charge</h4>";
				mediatorFeeHTML += "<p class='text'>A supplemental location charge may apply to sessions scheduled at a satellite location. This charge is typically a flat fee of $" + NewResolution.mediators[ID].getMediatorLocationCharge()[1];
				if (NewResolution.mediators[ID].getMediatorLocationCharge()[1] != NewResolution.mediators[ID].getMediatorLocationCharge()[2] && NewResolution.mediators[ID].getMediatorLocationCharge()[2] != '') mediatorFeeHTML += " to $" + NewResolution.mediators[ID].getMediatorLocationCharge()[2]; // if the 'from' and 'to' numbers are not the same AND the 'to' number is not blank, append a 'to' number to show a range.
				mediatorFeeHTML += " per session depending on location.</p>"; 
				}
			mediatorFeeHTML += "<h4>Other Services</h4>";
			mediatorFeeHTML	+= "<p class='text'>" + NewResolution.mediators[ID].getMediatorName() + " will prepare a Memorandum of Understanding to record your settle&shy;ment upon request.";
			if (NewResolution.mediators[ID].getMediatorServiceLevel()) // Mediator provides full service
				{
				mediatorFeeHTML += "&nbsp;" + NewResolution.mediators[ID].getMediatorName() + " will also assist in preparing a Marital Settlement Agreement and/or other court documents in connection with your case.";
				}
			else
				{
				mediatorFeeHTML += "&nbsp;" + NewResolution.mediators[ID].getMediatorName() + " will also provide third-party referrals and self-help resources for preparing any related court documents.";
				}
			mediatorFeeHTML += " In addition, you may request referrals to appraisers, CPAs, financial planners, therapists, and independent attorneys. <a href='s_custom.shtml'>Custom services</a> are also available.</p>";
			mediatorFeeHTML += "<h4>Payment</h4>";
			mediatorFeeHTML += "<p class='text'>";
			if (NewResolution.mediators[ID].getMediatorCardPolicy()[0])  // Display details of credit card policy according to first column element from the mediatorCardPolicy 2-D array[ID][col].
				{
				mediatorFeeHTML += "Parties may pay by cash, check, credit card, ATM/debit card, or electronic  transfer.";
				if (NewResolution.mediators[ID].getMediatorCardPolicy()[1]) mediatorFeeHTML += " Please note, a " + NewResolution.mediators[ID].getMediatorCardPolicy()[2] + "% processing fee applies to cedit card, ATM/debit card, and electronic transfers.";  // Include this line if the mediator levies a fee for credit cards.
				mediatorFeeHTML += "</p>";
				mediatorFeeHTML += "<br/><div style='position:relative; left:215px'><img src='/images/CreditCardLogos.jpg'></div><br>";
				}
			else
				{
				mediatorFeeHTML += "Parties may pay by cash or check.</p>";
				}
		showAll("holding_pen1");
		document.getElementById('holding_pen1').innerHTML = mediatorFeeHTML;
		}
	else
		{
		hideAll('holding_pen1'); //If the user resumes the 'Select a Locale' setting on the locales drop-down menu, then show the div with id="instructions" again.
		}
	return;
}

/*
This function generates the Google Maps URL for a mediator's principal office given that mediator's street address, city, and state to create a URL of this format: http://maps.google.com/maps?q=844+California+Street,+San+Francisco,+CA.
*/
function GoogleMapURL(ID)
{
	var mapString;
	mapString = "http://maps.google.com/maps?q=";
	mapString += NewResolution.mediators[ID].getMediatorPrincipalStreet().replace(/ /g,"\+"); // Replace the spaces in the street address with plus symbols. Note that the g regular-expression modifier indicates the need for a global search in order to find all of the occurrences in the string, not just the first space. (I could have alternatively used the join() method.)
	mapString += ",+";
	mapString += NewResolution.mediators[ID].getMediatorCity().replace(" ","+"); // Replace the spaces in the city with plus symbols
	mapString += ",+";
	mapString += NewResolution.mediators[ID].getMediatorState(); // Append the two-letter state code to the URL string
	return mapString;
}

/*
This function gets called on change of the locale drop-down (created inside GenerateLocalesDrop() above) on pages such as c_contact.shtml, s_mediators.shtml, and s_fees.shtml where I want to then show info for the mediator(s) who belong to the user-selected locale.
*/
function ShowMediatorInfo(index)
{
var index, counter, ID, num;
var showMediatorInfoHTML;
selectionStatusOfMediator = new Array();  // Holds the boolean values to show whether a mediator had his/her checkbox selected by the user. The index of the array is the mediator's ID e.g. selectionStatusOfMediator[207] = true would mean that the mediator of ID=207 has had his/her checkbox selected by the user. NOTE: I need to make this a global variable (even though it's defined inside the ShowMediatorInfo function) because it gets passed through the pure HTML (specifically, via an event-handler) of showMediatorInfoHTML that is dumped into holding_pen3 in c_contact.shtml. Because selectionStatusOfMediator is referenced in that place, it needs to have global scope. Inclusion of the var keyword would make selectionStatusOfMediator local to the function and result in selectionStatusOfMediator creating a 'variable is undefined' error when it's referenced in the event handler.
for (counter in mediatorIDsForUniqueLocale[index])
	{
	ID = mediatorIDsForUniqueLocale[index][counter];
	selectionStatusOfMediator[ID] = true; // Set (and reset) selectionStatusOfMediator to an array of all true values so that it's this way (i.e. reflective of the fact that all the displayed mediator(s) for a user-selected locale are checked by default) each time ShowMediatorInfo(form) function is called i.e. each time the user makes a change to the locale drop-down.
	}
showMediatorInfoHTML = ""; // Set/reset this to an empty string.
googleMapURL = new Array();
FisherYates(mediatorIDsForUniqueLocale[index]);
for (counter in mediatorIDsForUniqueLocale[index]) // Shuffle the array mediatorIDsForUniqueLocale[index] then loop through each of the IDs (i.e. columns) inside it, and show items of data (e.g. mediator's name, zip, telephone, etc.) if those items are not empty strings. Note: shuffling is performed by FisherYates() function to give no one mediator pole ranking position.
	{
	ID = mediatorIDsForUniqueLocale[index][counter];
	showMediatorInfoHTML += "<a name='med" + ID + "'></a>";
	if (!IEBrowserCheck()) showMediatorInfoHTML += "<br>";
	showMediatorInfoHTML += "<table width='670' cellpadding='0' cellspacing='0'>";
	showMediatorInfoHTML += "<tr><td width='470'>";
	showMediatorInfoHTML += "<div class='basictext' style='margin-left: 150px'>";
	showMediatorInfoHTML += "<b>" + (parseInt(counter) + 1) + ".&nbsp;&nbsp;" + NewResolution.mediators[ID].getMediatorName() + "</b><br>";
	if (NewResolution.mediators[ID].getMediatorEntityName() != "") showMediatorInfoHTML += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + NewResolution.mediators[ID].getMediatorEntityName() + "<br>";
	if (NewResolution.mediators[ID].getMediatorPrincipalAddressOther() != "") showMediatorInfoHTML += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + NewResolution.mediators[ID].getMediatorPrincipalAddressOther() + "<br>";
	if (NewResolution.mediators[ID].getMediatorPrincipalStreet() != "") showMediatorInfoHTML += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + NewResolution.mediators[ID].getMediatorPrincipalStreet() + "<br>";
	if (NewResolution.mediators[ID].getMediatorCity() != "") showMediatorInfoHTML += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + NewResolution.mediators[ID].getMediatorCity() + ",&nbsp;" + NewResolution.mediators[ID].getMediatorState() + "&nbsp;" + NewResolution.mediators[ID].getMediatorZip() + "<br><br>";
	if (NewResolution.mediators[ID].getMediatorTelephone() != "") showMediatorInfoHTML += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + NewResolution.mediators[ID].getMediatorTelephone() + "&nbsp;&nbsp;tel<br>";
	if (NewResolution.mediators[ID].getMediatorFax() != "") showMediatorInfoHTML += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + NewResolution.mediators[ID].getMediatorFax() + "&nbsp;&nbsp;fax<br>";
	if (NewResolution.mediators[ID].getMediatorEmail() != "") showMediatorInfoHTML += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + "<a href='mailto:" + NewResolution.mediators[ID].getMediatorEmail() + "'>" + NewResolution.mediators[ID].getMediatorEmail() + "</a><br><br><br>";
	showMediatorInfoHTML += "</div></td>";
	showMediatorInfoHTML += "<td width='145' align='left' valign='top'>";
if (NewResolution.mediators[ID].getMediatorCity() != "") { showMediatorInfoHTML += "<a href='" + GoogleMapURL(ID) + "' onClick=\"wintasticthirdparty(\'" + GoogleMapURL(ID) + "\'); return false;\"><img class='mapthumb1' src='/images/MapThumb1.jpg'><br></a><span class='basictextsmaller' style='position: relative; left: 20px'>Click map for directions</span>" } else { showMediatorInfoHTML += " "; }; // If the mediator has identified a city, assume that he/she has a principal office location and include a link to a Google map of that location.
	showMediatorInfoHTML += "</td>";
	showMediatorInfoHTML += "<td width='55' align='right' valign='top'>";
	showMediatorInfoHTML += "<input type='checkbox' style='position: relative; top: 40px' name='selectee" + ID + "' value='" + ID + "' CHECKED onclick='if (this.form.selectee" + ID + ".checked) { selectionStatusOfMediator[" + ID + "] = true; } else { selectionStatusOfMediator[" + ID + "] = false; }; GenerateFormRecipients(selectionStatusOfMediator);'>";  // Call GenerateFormRecipients function to update the hidden recipients field every time the user clicks a selection checkbox.
	showMediatorInfoHTML += "</td></tr></table>";
	showMediatorInfoHTML += "<HR align='left' size='1px' noshade color='#FF9900' class='formdivider3'>";
	}
GenerateFormRecipients(selectionStatusOfMediator);  // Also call GenerateFormRecipients function here to establish the initial list of recipient(s), which should be all the mediators for the user-selected locale since the default is to show all such mediators' check-boxes as selected.
document.getElementById('holding_pen1').innerHTML = showMediatorInfoHTML;
return;
}

/*
This function, which simply places focus on the first element in a form, is called by including the following JavaScript just before the <form> tag in the HTML document: window.onload = FocusFirst
*/
function FocusFirst()
{
	if (document.forms.length > 0 && document.forms[0].elements.length > 0)
		document.forms[0].elements[0].focus();
}

/*
Function to test for IE, which tends to space things more generously that Firefox/NS/Safari. I use this function to add spacing between <h1> title and the states dropdown menu on certain pages (e.g. property.shtml) when the browser isn't IE.
Source code for a fuller version than my simplified version is at: http://www.netmechanic.com/news/vol3/javascript_no15.htm
*/
function IEBrowserCheck()
{
 if(navigator.appName == "Microsoft Internet Explorer")
	{
 	return true;
	}
else
	{
	return false;
	}
}

/*
Function to test for Safari, which is used within coremediatorfunctions.js within ShowMediatorInfo() function to control Safari's spacing for contact.shtml page. Source code for a fuller version than my simplified version is at: http://www.netmechanic.com/news/vol3/javascript_no15.htm
*/
function SafariBrowserCheck()
{
 if (navigator.userAgent.indexOf("Safari") != -1)
	{
 	return true;
	}
else
	{
	return false;
	}
}

// Function returns 'true' when input is an integer, and 'false' otherwise.
function IsInteger(s)
{
    return Math.ceil(s) == Math.floor(s);
}

// General client-side include function. It currently includes the copyright infringement notice on pages such as divandsep.shtml, support.shtml, and property.shtml. Note: I could easily use this function to include other notices by defining other variables (e.g. str_other) and then setting document.getElementById(id).innerHTML = str_other. Note also that the date year is set dynamically using a method of Javascript's Date object.
function IncludeNotice(id)
{
var str, thedate, fullyear;
thedate = new Date(); // set to the current date
fullyear = thedate.getFullYear();
str = "<div id='notice'>"
str += "<b>Disclaimer:</b>&nbsp;The foregoing is general information, not legal advice. Family law is subject to continual legislative review and varying judicial interpretation, and the particulars of your situation are unique. Consult an experienced family law attorney for specific legal advice. New Resolution LLC is not a law firm, and its network of independent mediators &mdash; even when trained as attorneys &mdash; cannot provide legal advice while acting as mediators.";
str += "</div><br>"
str += "<div id='notice'>"
str += "<b>Copyright Notice:</b>&nbsp;&copy; " + fullyear + " New Resolution LLC. Unauthorized reproduction or any other infringement of this copyright is strictly prohibited. This copyright notice will be enforced.";
str += "</div>"
document.getElementById(id).innerHTML = str;
}
